# Generated by Django 4.0.3 on 2022-10-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('AU', 'Account Upload'), ('AP', 'Account Purchase')], max_length=2, null=True),
        ),
    ]
