# Generated by Django 4.0.3 on 2022-10-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('P', 'Paypal'), ('C', 'Card'), ('W', 'Wallet')], max_length=2, null=True),
        ),
    ]
