# Generated by Django 4.0.3 on 2022-10-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PC', 'Paypal or Card'), ('W', 'Wallet')], max_length=2, null=True),
        ),
    ]
