# Generated by Django 4.2.29 on 2026-03-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('PC', 'Paypal or Card'), ('W', 'Wallet'), ('BTC', 'Bitcoin')], max_length=3, null=True),
        ),
    ]
