# Generated by Django 4.0.3 on 2022-09-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mode',
            field=models.CharField(blank=True, choices=[('S', 'Seller'), ('B', 'Buyer')], max_length=2, null=True),
        ),
    ]
