# Generated by Django 4.0.3 on 2022-09-15 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('profiles', '0002_userprofile_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('date_uploaded_on_market', models.DateTimeField()),
                ('date_removed_from_market', models.DateTimeField()),
                ('platform', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('thumb_nail', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('selling_price', models.FloatField(blank=True, null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('market_fee', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('S', 'Sold'), ('D', 'Draft'), ('OS', 'Onsale')], max_length=2)),
                ('ratings', models.FloatField(blank=True, null=True)),
                ('reviews', models.FloatField(blank=True, null=True)),
                ('number_of_completed_orders', models.FloatField(blank=True, null=True)),
                ('chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
                ('current_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile')),
                ('images', models.ManyToManyField(blank=True, to='accounts.image')),
                ('tags', models.ManyToManyField(blank=True, to='accounts.tag')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_owner', to='profiles.userprofile')),
            ],
        ),
    ]
