# Generated by Django 4.0.3 on 2022-09-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_removed_from_market',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date_uploaded_on_market',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
