# Generated by Django 4.0.3 on 2022-09-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_date_removed_from_market_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('S', 'Sold'), ('D', 'Draft'), ('OS', 'Onsale'), ('IC', 'InsideCart')], max_length=2),
        ),
    ]
