# Generated by Django 4.0.3 on 2022-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='has_test',
            field=models.BooleanField(default=False),
        ),
    ]
