# Generated by Django 4.0.3 on 2022-10-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_has_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verified_and_securely_transfared',
            field=models.BooleanField(default=False),
        ),
    ]
