# Generated by Django 4.0.3 on 2022-10-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_reference_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='percent_of_complete_details',
            field=models.FloatField(default=0.0),
        ),
    ]
