# Generated by Django 4.0.3 on 2022-10-14 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_percent_of_complete_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_time_account_was_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='market_fee_payment_completed',
            field=models.BooleanField(default=False),
        ),
    ]
