# Generated by Django 4.0.3 on 2022-10-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_last_time_account_was_edited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='no_of_times_price_has_changed',
            field=models.IntegerField(default=0),
        ),
    ]
