# Generated by Django 4.0.3 on 2022-10-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_market_fee_after_price_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_searches', models.IntegerField(default=0)),
                ('no_of_account_views', models.IntegerField(default=0)),
                ('no_of_wishlist', models.IntegerField(default=0)),
                ('no_of_pending_carts', models.IntegerField(default=0)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
