# Generated by Django 4.0.3 on 2022-10-17 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_wallet_alter_userprofile_profile_settings_and_more'),
        ('accounts', '0011_impression'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impression',
            name='no_of_account_views',
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='impression',
            name='internal_views',
            field=models.ManyToManyField(blank=True, related_name='Internal views+', to='accounts.view'),
        ),
        migrations.AddField(
            model_name='impression',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='View+', to='accounts.view'),
        ),
    ]
