# Generated by Django 5.2.2 on 2025-06-10 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_impression_no_of_account_views_view_and_more'),
        ('profiles', '0006_creditcard_paypalaccount_userprofile_credit_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('step_number', models.IntegerField()),
                ('text_body', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=None)),
                ('video', models.FileField(blank=True, null=True, upload_to=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='has_test',
        ),
        migrations.AddField(
            model_name='account',
            name='platform_type',
            field=models.CharField(blank=True, choices=[('FR', 'Freelancing'), ('IG', 'Instagram'), ('TK', 'Tiktok'), ('YT', 'Youtube'), ('TT', 'X')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_email', models.CharField(blank=True, max_length=512, null=True)),
                ('login_username', models.CharField(blank=True, max_length=512, null=True)),
                ('login_email_password', models.CharField(blank=True, max_length=512, null=True)),
                ('recovery_email', models.CharField(blank=True, max_length=512, null=True)),
                ('recovery_email_password', models.CharField(blank=True, max_length=512, null=True)),
                ('login_gmail', models.CharField(blank=True, max_length=512, null=True)),
                ('login_gmail_password', models.CharField(blank=True, max_length=512, null=True)),
                ('recovery_gmail', models.CharField(blank=True, max_length=512, null=True)),
                ('recovery_gmail_password', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('allowed_viewers', models.ManyToManyField(blank=True, to='profiles.userprofile')),
            ],
        ),
    ]
