# Generated by Django 4.2.29 on 2026-03-10 03:28

import accounts.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_securitystep_remove_account_has_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='login_email',
            field=accounts.encryption.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='login_email_password',
            field=accounts.encryption.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='login_gmail',
            field=accounts.encryption.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='login_gmail_password',
            field=accounts.encryption.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='recovery_email',
            field=accounts.encryption.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='recovery_email_password',
            field=accounts.encryption.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='recovery_gmail',
            field=accounts.encryption.EncryptedCharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='recovery_gmail_password',
            field=accounts.encryption.EncryptedCharField(blank=True, null=True),
        ),
    ]
