# Generated by Django 4.0.3 on 2022-09-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnswerFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='InstructionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction_file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='timer',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='exam',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(blank=True, choices=[('TA', 'Take Away'), ('QA', 'Question and Answer')], max_length=2),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answers', models.ManyToManyField(blank=True, to='exams.answer')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='exams.answer')),
            ],
        ),
        migrations.AddField(
            model_name='attempt',
            name='answer_files',
            field=models.ManyToManyField(blank=True, to='exams.answerfile'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='answers',
            field=models.ManyToManyField(blank=True, to='exams.answer'),
        ),
        migrations.AddField(
            model_name='exam',
            name='instruction_files',
            field=models.ManyToManyField(blank=True, to='exams.instructionfile'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, to='exams.question'),
        ),
    ]
