# Generated by Django 4.0.3 on 2022-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_answer_answerfile_instructionfile_attempt_timer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='completed_questions',
            field=models.ManyToManyField(blank=True, to='exams.question'),
        ),
    ]
