# Generated by Django 4.0.3 on 2022-10-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_attempt_completed_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='type',
            new_name='exam_type',
        ),
    ]
