# Generated by Django 4.0.3 on 2022-10-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_rename_type_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='no_of_questions',
            field=models.IntegerField(default=0),
        ),
    ]
