# Generated by Django 4.0.3 on 2022-10-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_exam_no_of_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='pass_mark',
        ),
        migrations.AddField(
            model_name='exam',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_number_of_student_slots',
            field=models.IntegerField(default=0),
        ),
    ]
