# Generated by Django 4.0.3 on 2022-10-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_exam_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='date_submitted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
