# Generated by Django 4.0.3 on 2022-10-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_attempt_date_submitted_exam_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTypeInstructions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('exam_type', models.CharField(choices=[('TA', 'Take Away'), ('QA', 'Question and Answer')], max_length=2)),
                ('instructions', models.TextField()),
            ],
        ),
    ]
