# Generated by Django 4.0.3 on 2022-09-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_has_test'),
        ('shop', '0002_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='accounts.account'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='accounts',
            field=models.ManyToManyField(blank=True, to='accounts.account'),
        ),
    ]
