# Generated by Django 4.0.3 on 2022-10-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_has_test'),
        ('shop', '0003_cart_accounts_wishlist_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='accounts',
        ),
        migrations.AddField(
            model_name='cart',
            name='accounts_to_be_purchased',
            field=models.ManyToManyField(blank=True, related_name='Accounts to be purchased+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='cart',
            name='accounts_to_be_uploaded_on_the_market',
            field=models.ManyToManyField(blank=True, related_name='Accouts to be uploadedon the market+', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='cart',
            name='pending_accounts',
            field=models.ManyToManyField(blank=True, related_name='Pending accounts+', to='accounts.account'),
        ),
    ]
