# Generated by Django 4.0.3 on 2022-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_market_fee_after_price_change'),
        ('shop', '0004_remove_cart_accounts_cart_accounts_to_be_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='accounts_to_be_changed_price',
            field=models.ManyToManyField(blank=True, null=True, related_name='Accounts which the prices are being changed+', to='accounts.account'),
        ),
    ]
