# Generated by Django 4.2.29 on 2026-03-10 03:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0007_alter_order_payment_method'),
        ('profiles', '0006_creditcard_paypalaccount_userprofile_credit_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoltagePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_msats', models.BigIntegerField(default=0)),
                ('btc_price_at_creation', models.DecimalField(blank=True, decimal_places=2, help_text='BTC/USD price at the moment the payment was created.', max_digits=12, null=True)),
                ('payment_kind', models.CharField(choices=[('bolt11', 'Lightning (BOLT11)'), ('onchain', 'On-chain Bitcoin'), ('bip21', 'Unified BIP21 (Lightning + On-chain)')], default='bip21', max_length=10)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('receiving', 'Receiving (Awaiting Payment)'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='generating', max_length=20)),
                ('network', models.CharField(choices=[('mainnet', 'Bitcoin Mainnet'), ('mutinynet', 'Mutinynet (Staging / Testnet)')], default='mutinynet', max_length=20)),
                ('btc_address', models.CharField(blank=True, max_length=200)),
                ('lightning_invoice', models.TextField(blank=True)),
                ('bip21_uri', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('voltage_response', models.JSONField(blank=True, default=dict)),
                ('webhook_data', models.JSONField(blank=True, default=dict)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voltage_payment', to='payments.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voltage_payments', to='profiles.userprofile')),
            ],
            options={
                'verbose_name': 'Voltage Payment',
                'verbose_name_plural': 'Voltage Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoltageWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(max_length=100, unique=True)),
                ('organization_id', models.CharField(max_length=100)),
                ('environment_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('network', models.CharField(choices=[('mainnet', 'Bitcoin Mainnet'), ('mutinynet', 'Mutinynet (Staging / Testnet)')], max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only one wallet should be active per network.')),
                ('is_staging', models.BooleanField(default=True, help_text='True = staging / testnet wallet.')),
                ('balance_msats', models.BigIntegerField(default=0, help_text='Cached balance in millisatoshis. Use Admin action to sync.')),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voltage Wallet',
                'verbose_name_plural': 'Voltage Wallets',
                'ordering': ['-is_active', 'network'],
            },
        ),
        migrations.CreateModel(
            name='VoltageWebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_id', models.CharField(blank=True, max_length=100)),
                ('webhook_url', models.URLField()),
                ('shared_secret', models.CharField(blank=True, help_text='Voltage shared_secret — shown once at webhook creation. Store immediately.', max_length=512)),
                ('environment_id', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('events', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voltage Webhook Config',
                'verbose_name_plural': 'Voltage Webhook Configs',
            },
        ),
        migrations.CreateModel(
            name='VoltageWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage_payment_id', models.CharField(blank=True, max_length=100)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('processed_ok', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='voltage_payments.voltagepayment')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='voltagepayment',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voltage_payments.voltagewallet'),
        ),
    ]
